### ISSUE TITLE
ViTAR代码开源？

### ISSUE THREAD

**Issue by JoshonSmith** [kyegomez/ViTAR#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TonFard** [comment]
模型的代码没有开源吗

**Comment by qgh1223qgh** [comment]
Hope your code will be released soon
interested in your work

**Comment by Sparsh913** [comment]
When would the code be released?

**Comment by kyegomez** [comment]
@Sparsh913 @JoshonSmith it's finished, try it out now!

**Comment by Sparsh913** [comment]
That's great, thanks! I'll check it out!
